# Generated by Django 6.0.5 on 2026-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tour_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên danh mục"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Các danh mục",
            },
        ),
        migrations.AddField(
            model_name="tour",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="tours",
                to="tours.category",
                verbose_name="Danh mục",
            ),
        ),
    ]
