# Generated by Django 6.0.4 on 2026-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Link ảnh'),
        ),
    ]
